name: LLM Code Review Example

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git diff to work properly
      
      - name: LLM Code Review
        uses: ./
        with:
          llm_provider: 'claude'  # or 'openai'
          claude_api_key: ${{ secrets.CLAUDE_API_KEY }}
          # openai_api_key: ${{ secrets.OPENAI_API_KEY }}  # if using OpenAI
          path_to_files: 'src/,packages/'  # Multiple paths supported
          # base_branch: 'develop'  # Optional - auto-detected from PR
          max_tokens: '2000'
          temperature: '0.3' 