name: Update Latest Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on any version tag (v1.0.0, v2.1.3, etc.)

jobs:
  update-latest:
    runs-on: ubuntu-latest
    # Only run if this is a new tag (not a force push to existing tag)
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for tag operations
          token: ${{ secrets.SEERA_FRONTEND_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Get current tag
        id: current-tag
        run: |
          # Extract tag name from ref (e.g., refs/tags/v1.12.0 -> v1.12.0)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Current tag: $TAG_NAME"
      
      - name: Update latest tag
        run: |
          # Delete local latest tag if it exists
          git tag -d latest 2>/dev/null || true
          
          # Create new latest tag pointing to current version
          git tag latest ${{ steps.current-tag.outputs.tag_name }}
          
          # Push the latest tag (force push to update it)
          git push origin latest --force
          
          echo "✅ Updated 'latest' tag to point to ${{ steps.current-tag.outputs.tag_name }}"
      
      - name: Verify latest tag
        run: |
          # Fetch all tags to verify
          git fetch --tags
          
          # Show what latest tag points to
          LATEST_COMMIT=$(git rev-parse latest)
          CURRENT_COMMIT=$(git rev-parse ${{ steps.current-tag.outputs.tag_name }})
          
          echo "Latest tag commit: $LATEST_COMMIT"
          echo "Current version commit: $CURRENT_COMMIT"
          
          if [ "$LATEST_COMMIT" = "$CURRENT_COMMIT" ]; then
            echo "✅ Latest tag successfully updated!"
          else
            echo "❌ Latest tag update failed!"
            exit 1
          fi
