name: Update Latest Tag

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["Create Release and Update Latest Tag"]
    types:
      - completed
    branches:
      - master

jobs:
  update-latest:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN_SECRET }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get current tag
        id: get-tag
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            # Extract tag from push event
            TAG_NAME=${GITHUB_REF#refs/tags/}
          else
            # Extract tag from workflow run (get the latest v* tag)
            TAG_NAME=$(git tag --sort=-version:refname | grep '^v' | head -1)
          fi
          
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "🏷️ Current tag: $TAG_NAME"
          
          if [ -z "$TAG_NAME" ]; then
            echo "❌ No version tag found"
            exit 1
          fi

      - name: Update latest tag
        run: |
          # Delete existing latest tag if it exists
          git tag -d latest 2>/dev/null || true
          git push origin :refs/tags/latest 2>/dev/null || true
          
          # Create new latest tag pointing to current version
          git tag latest ${{ steps.get-tag.outputs.tag_name }}
          git push origin latest
          
          echo "✅ Latest tag updated to point to ${{ steps.get-tag.outputs.tag_name }}"

      - name: Verify latest tag
        run: |
          # Verify latest tag points to the correct commit
          LATEST_COMMIT=$(git rev-parse latest)
          VERSION_COMMIT=$(git rev-parse ${{ steps.get-tag.outputs.tag_name }})
          
          if [ "$LATEST_COMMIT" = "$VERSION_COMMIT" ]; then
            echo "✅ Latest tag verification successful"
            echo "Latest tag points to: ${{ steps.get-tag.outputs.tag_name }}"
            echo "Commit hash: $LATEST_COMMIT"
          else
            echo "❌ Latest tag verification failed"
            echo "Latest tag commit: $LATEST_COMMIT"
            echo "Version tag commit: $VERSION_COMMIT"
            exit 1
          fi
